DATA_PATH = "data/"
EMBEDDINGS_PATH = "embeddings/"
MODEL_PATH = "save_models/"
META_PATH = "meta/"
FASTTEXT_VECTOR_PATH = EMBEDDINGS_PATH + "wiki-news-300d-1M.vec"
GOOGLE_VECTOR_PATH = EMBEDDINGS_PATH + "GoogleNews-vectors-negative300.bin"

# ------------------- classifiers ----------------------------
SENT_MODEL_PATH = MODEL_PATH + "sent/"
NER_MODEL_PATH = MODEL_PATH + "ner/"
POS_MODEL_PATH = MODEL_PATH + "pos/"
CHUNK_MODEL_PATH = MODEL_PATH + "chunk/"


# ------------------- classifiers ----------------------------
SENT_ROOT = 'data/sentiment/'
SENT_EMBEDDING_PATH = "./embeddings/sentiment/"
SENT_TEST = SENT_ROOT + "test.txt"
SENT_TRAIN = SENT_ROOT + "train.txt"
SENT_VALID = SENT_ROOT + "valid.txt"

SENT_WORD2IND_PATH = SENT_EMBEDDING_PATH + "word2ind.p"
SENT_IND2WORD_PATH = SENT_EMBEDDING_PATH + "ind2word.p"
SENT_WORD2VEC_VOCAB_PATH = SENT_EMBEDDING_PATH + "word2vec.p"

SENT_META_EMBEDDING_PATH = SENT_EMBEDDING_PATH + "meta2vec.p"
SENT_WORD2VEC_EMBEDDING_PATH = SENT_EMBEDDING_PATH + "word2vec.p"
SENT_GLOVE_EMBEDDING_PATH = SENT_EMBEDDING_PATH + "glove.p"
SENT_HPCA_EMBEDDING_PATH = SENT_EMBEDDING_PATH + "hpca.p"
SENT_FASTTEXT_EMBEDDING_PATH = SENT_EMBEDDING_PATH + "fasttext.p"
SENT_LEX_EMBEDDING_PATH = SENT_EMBEDDING_PATH + "lex2vec.p"

SENT_ID2VEC_VOCAB_PATH = SENT_EMBEDDING_PATH + "id2vec.p"
SENT_CNN_MODEL_PATH = MODEL_PATH + "cnn_model.p"
SENT_LSTM_MODEL_PATH = MODEL_PATH + "lstm_model.p"
SENT_RNN_MODEL_PATH = MODEL_PATH + "rnn_model.p"
SENT_GRU_MODEL_PATH = MODEL_PATH + "gru_model.p"
SENT_FASTTEXT_TRAINED_VECTOR_PATH = SENT_EMBEDDING_PATH + "fasttext.vec"
SENT_WORD2VEC_TRAINED_VECTOR_PATH = SENT_EMBEDDING_PATH + "word2vec.bin"
SENT_KD_TREE_PATH = SENT_EMBEDDING_PATH + "kdt.p"
SENT_HDBSCAN_PATH = SENT_EMBEDDING_PATH + "hdbscan.p"

# ------------------- NER ----------------------------
NER_ROOT = './data/ner/'
NER_EMBEDDING_PATH = "./embeddings/ner/"


NER_TEST = NER_ROOT + "test.txt"
NER_TRAIN = NER_ROOT + "train.txt"
NER_VALID = NER_ROOT + "valid.txt"
NER_NEIGHBOR2VEC_PATH = NER_EMBEDDING_PATH + "neighbor2vec.p"
NER_WORD2IND_PATH = NER_EMBEDDING_PATH + "word2ind.p"
NER_IND2WORD_PATH = NER_EMBEDDING_PATH + "ind2word.p"
NER_WORD2VEC_VOCAB_PATH = NER_EMBEDDING_PATH + "word2vec.p"
NER_ID2VEC_VOCAB_PATH = NER_EMBEDDING_PATH + "id2vec.p"
NER_CNN_MODEL_PATH = NER_EMBEDDING_PATH + "cnn_model.p"
NER_LSTM_MODEL_PATH = NER_EMBEDDING_PATH + "lstm_model.p"
NER_RNN_MODEL_PATH = NER_EMBEDDING_PATH + "rnn_model.p"
NER_GRU_MODEL_PATH = NER_EMBEDDING_PATH + "gru_model.p"
NER_FASTTEXT_TRAINED_VECTOR_PATH = NER_EMBEDDING_PATH + "fasttext.vec"
NER_WORD2VEC_TRAINED_VECTOR_PATH = NER_EMBEDDING_PATH + "word2vec.bin"
NER_KD_TREE_PATH = NER_EMBEDDING_PATH + "kdt.p"
NER_HDBSCAN_PATH = NER_EMBEDDING_PATH + "hdbscan.p"

NER_META_EMBEDDING_PATH = NER_EMBEDDING_PATH + "meta2vec.p"
NER_WORD2VEC_EMBEDDING_PATH = NER_EMBEDDING_PATH + "word2vec.p"
NER_GLOVE_EMBEDDING_PATH = NER_EMBEDDING_PATH + "glove.p"
NER_HPCA_EMBEDDING_PATH = NER_EMBEDDING_PATH + "hpca.p"
NER_FASTTEXT_EMBEDDING_PATH = NER_EMBEDDING_PATH + "fasttext.p"
NER_LEX_EMBEDDING_PATH = NER_EMBEDDING_PATH + "lex2vec.p"


# ------------------- POS ----------------------------
POS_ROOT = './data/udpos/en-ud-v2/en-ud-tag.v2.'
POS_EMBEDDING_PATH = "./embeddings/pos/"

POS_TEST = POS_ROOT + "test.txt"
POS_TRAIN = POS_ROOT + "train.txt"
POS_VALID = POS_ROOT + "valid.txt"
POS_NEIGHBOR2VEC_PATH = POS_EMBEDDING_PATH + "neighbor2vec.p"
POS_WORD2IND_PATH = POS_EMBEDDING_PATH + "word2ind.p"
POS_IND2WORD_PATH = POS_EMBEDDING_PATH + "ind2word.p"
POS_WORD2VEC_VOCAB_PATH = POS_EMBEDDING_PATH + "word2vec.p"
POS_ID2VEC_VOCAB_PATH = POS_EMBEDDING_PATH + "id2vec.p"
POS_CNN_MODEL_PATH = MODEL_PATH + "cnn_model.p"
POS_LSTM_MODEL_PATH = MODEL_PATH + "lstm_model.p"
POS_RNN_MODEL_PATH = MODEL_PATH + "rnn_model.p"
POS_GRU_MODEL_PATH = MODEL_PATH + "gru_model.p"
POS_FASTTEXT_TRAINED_VECTOR_PATH = POS_EMBEDDING_PATH + "fasttext.vec"
POS_WORD2VEC_TRAINED_VECTOR_PATH = POS_EMBEDDING_PATH + "word2vec.bin"
POS_KD_TREE_PATH = POS_EMBEDDING_PATH + "kdt.p"
POS_HDBSCAN_PATH = POS_EMBEDDING_PATH + "hdbscan.p"

POS_META_EMBEDDING_PATH = POS_EMBEDDING_PATH + "meta2vec.p"
POS_WORD2VEC_EMBEDDING_PATH = POS_EMBEDDING_PATH + "word2vec.p"
POS_GLOVE_EMBEDDING_PATH = POS_EMBEDDING_PATH + "glove.p"
POS_HPCA_EMBEDDING_PATH = POS_EMBEDDING_PATH + "hpca.p"
POS_FASTTEXT_EMBEDDING_PATH = POS_EMBEDDING_PATH + "fasttext.p"
POS_LEX_EMBEDDING_PATH = POS_EMBEDDING_PATH + "lex2vec.p"

# ------------------- chunking ----------------------------

CHUNKING_ROOT = 'data/chunking/'
CHUNKING_EMBEDDING_PATH = "embeddings/chunking/"


CHUNKING_TEST = CHUNKING_ROOT + "test.txt"
CHUNKING_TRAIN = CHUNKING_ROOT + "train.txt"

CHUNKING_NEIGHBOR2VEC_PATH = CHUNKING_EMBEDDING_PATH + "neighbor2vec.p"
CHUNKING_WORD2IND_PATH = CHUNKING_EMBEDDING_PATH + "word2ind.p"
CHUNKING_IND2WORD_PATH = CHUNKING_EMBEDDING_PATH + "ind2word.p"
CHUNKING_WORD2VEC_VOCAB_PATH = CHUNKING_EMBEDDING_PATH + "word2vec.p"
CHUNKING_ID2VEC_VOCAB_PATH = CHUNKING_EMBEDDING_PATH + "id2vec.p"

CHUNKING_CNN_MODEL_PATH = MODEL_PATH + "chunking/cnn_model.p"
CHUNKING_LSTM_MODEL_PATH = MODEL_PATH + "chunking/lstm_model.p"
CHUNKING_RNN_MODEL_PATH = MODEL_PATH + "chunking/rnn_model.p"
CHUNKING_GRU_MODEL_PATH = MODEL_PATH + "chunking/gru_model.p"

CHUNKING_FASTTEXT_TRAINED_VECTOR_PATH = CHUNKING_EMBEDDING_PATH + "fasttext.vec"
CHUNKING_WORD2VEC_TRAINED_VECTOR_PATH = CHUNKING_EMBEDDING_PATH + "word2vec.bin"
CHUNKING_KD_TREE_PATH = CHUNKING_EMBEDDING_PATH + "chunking/kdt.p"
CHUNKING_HDBSCAN_PATH = CHUNKING_EMBEDDING_PATH + "chunking/hdbscan.p"


CHUNKING_META_EMBEDDING_PATH = CHUNKING_EMBEDDING_PATH + "meta2vec.p"
CHUNKING_WORD2VEC_EMBEDDING_PATH = CHUNKING_EMBEDDING_PATH + "word2vec.p"
CHUNKING_GLOVE_EMBEDDING_PATH = CHUNKING_EMBEDDING_PATH + "glove.p"
CHUNKING_HPCA_EMBEDDING_PATH = CHUNKING_EMBEDDING_PATH + "hpca.p"
CHUNKING_FASTTEXT_EMBEDDING_PATH = CHUNKING_EMBEDDING_PATH + "fasttext.p"
CHUNKING_LEX_EMBEDDING_PATH = CHUNKING_EMBEDDING_PATH + "lex2vec.p"


# ------------------- Results ----------------------------
WRITE_ROOT = "results/"
CHUNKING_WRITE_ROOT = WRITE_ROOT + "chunking/"
UDPOS_WRITE_ROOT = WRITE_ROOT + "udpos/"
UDPOS_WRITE_ROOT = WRITE_ROOT + "udpos/"
NER_WRITE_ROOT = WRITE_ROOT + "ner/"